export enum TipoPagamentoEnum {
  BOLETO = 'BOLETO',
  CARTAODECREDITO = 'CARTAO DE CREDITO',
  CARTAODEDEBITO = 'CARTAO DE DEBITO',
  CHEQUE = 'CHEQUE',
  DINHEIRO = 'DINHEIRO',
  PIX = 'PIX',
  TRANSFERENCIA = 'TRANSFERENCIA',
}